"""Remove EventManager model and tables

Revision ID: 08cbfccaa094
Revises: 6c10d353e020
Create Date: 2025-07-07 12:41:16.430230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08cbfccaa094'
down_revision = '6c10d353e020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_manager_associations')
    op.drop_table('event_managers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_managers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=15), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_manager_associations',
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('event_manager_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['event_manager_id'], ['event_managers.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'event_manager_id')
    )
    # ### end Alembic commands ###
