"""Add lockout field to Member model for security

Revision ID: 13667fded83d
Revises: c015ca6372d9
Create Date: 2025-07-15 14:42:15.558041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13667fded83d'
down_revision = 'c015ca6372d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the column as nullable with default value
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lockout', sa.Boolean(), nullable=True, default=False))
    
    # Step 2: Update all existing rows to have the default value
    op.execute("UPDATE member SET lockout = 0 WHERE lockout IS NULL")
    
    # Step 3: Make the column NOT NULL
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('lockout', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('lockout')

    # ### end Alembic commands ###
