"""Add series_name field to bookings table

Revision ID: 338b3af821c4
Revises: 23f59a33967b
Create Date: 2025-08-10 14:04:00.671759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338b3af821c4'
down_revision = '23f59a33967b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_name', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('series_name')

    # ### end Alembic commands ###
