"""Removed the pin from the posts table

Revision ID: 3694bfae84d1
Revises: 1d9b67494779
Create Date: 2025-04-19 18:32:32.764028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3694bfae84d1'
down_revision = '1d9b67494779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('pin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
