"""Add roll-up booking support with BookingPlayer model and extended Booking fields

Revision ID: 3d2b4c8f08a3
Revises: 13667fded83d
Create Date: 2025-07-15 17:45:24.130969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2b4c8f08a3'
down_revision = '13667fded83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('response_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['member.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('organizer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('organizer_notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_bookings_organizer_id', 'member', ['organizer_id'], ['id'])
    
    # Update existing bookings to have 'event' as default booking_type
    op.execute("UPDATE bookings SET booking_type = 'event' WHERE booking_type IS NULL")
    
    # Now make booking_type non-nullable
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('booking_type', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bookings_organizer_id', type_='foreignkey')
        batch_op.drop_column('organizer_notes')
        batch_op.drop_column('organizer_id')
        batch_op.drop_column('booking_type')

    op.drop_table('booking_players')
    # ### end Alembic commands ###
