"""Removed Bookings model

Revision ID: 59cec05170fe
Revises: 5c21cb22e71f
Create Date: 2025-04-08 18:07:53.103478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59cec05170fe'
down_revision = '5c21cb22e71f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index('ix_booking_date')
        batch_op.drop_index('ix_booking_member_id')
        batch_op.drop_index('ix_booking_timestamp')

    op.drop_table('booking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('time', sa.VARCHAR(length=5), nullable=False),
    sa.Column('duration', sa.INTEGER(), nullable=False),
    sa.Column('notes', sa.VARCHAR(length=140), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name='fk_booking_member_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index('ix_booking_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_booking_member_id', ['member_id'], unique=False)
        batch_op.create_index('ix_booking_date', ['date'], unique=False)

    # ### end Alembic commands ###
