"""Add EventOwner model, gender and scoring fields to Event, and many-to-many relationship

Revision ID: 67edad2468fa
Revises: b9a068d4a434
Create Date: 2025-07-07 09:21:04.173418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67edad2468fa'
down_revision = 'b9a068d4a434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_owner_associations',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['event_owner_id'], ['event_owners.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'event_owner_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.Integer(), nullable=False, server_default='4'))  # Default to "Open"
        batch_op.add_column(sa.Column('scoring', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('scoring')
        batch_op.drop_column('gender')

    op.drop_table('event_owner_associations')
    op.drop_table('event_owners')
    # ### end Alembic commands ###
