"""Add vs and home_away fields to bookings

Revision ID: 6dade49adcf0
Revises: ed9d4c7fe38d
Create Date: 2025-07-11 09:22:54.747962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dade49adcf0'
down_revision = 'ed9d4c7fe38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vs', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('home_away', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('home_away')
        batch_op.drop_column('vs')

    # ### end Alembic commands ###
