"""Add status and finalized_at fields to Team model

Revision ID: 6ed6bbb551c3
Revises: c3d062b06b93
Create Date: 2025-08-06 15:34:01.147165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed6bbb551c3'
down_revision = 'c3d062b06b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'))
        batch_op.add_column(sa.Column('finalized_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('finalized_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
