"""Added Booking model

Revision ID: 7014e9a8128a
Revises: 3694bfae84d1
Create Date: 2025-04-20 15:29:28.681248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7014e9a8128a'
down_revision = '3694bfae84d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('session', sa.Integer(), nullable=False),
    sa.Column('rink', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###
