"""Remove rink column from bookings table

Revision ID: 775f9d9c4fd3
Revises: 88e2ccad1374
Create Date: 2025-07-06 17:19:15.235304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775f9d9c4fd3'
down_revision = '88e2ccad1374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('rink_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('rink')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rink', sa.INTEGER(), nullable=False))
        batch_op.alter_column('rink_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
