"""Replace rink field with rink_count in booking model

Revision ID: 88e2ccad1374
Revises: 7014e9a8128a
Create Date: 2025-07-06 17:14:36.586399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e2ccad1374'
down_revision = '7014e9a8128a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rink_count', sa.Integer(), nullable=True))
    
    # Set default value of 1 for all existing records
    op.execute("UPDATE bookings SET rink_count = 1")
    
    # Now make the column NOT NULL and drop the old rink column
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('rink_count', nullable=False)
        batch_op.drop_column('rink')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rink', sa.INTEGER(), nullable=False))
        batch_op.drop_column('rink_count')

    # ### end Alembic commands ###
