"""Add format column to events table

Revision ID: 99cb96046901
Revises: 08cbfccaa094
Create Date: 2025-07-07 15:13:16.654168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99cb96046901'
down_revision = '08cbfccaa094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format', sa.Integer(), nullable=False, server_default='5'))  # Default to "Fours - 2 Wood"

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('format')

    # ### end Alembic commands ###
