"""Added indexing to members names

Revision ID: 9ca68375a1c9
Revises: 875cde57901e
Create Date: 2025-04-08 15:32:30.575837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca68375a1c9'
down_revision = '875cde57901e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_firstname'), ['firstname'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_lastname'), ['lastname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_lastname'))
        batch_op.drop_index(batch_op.f('ix_member_firstname'))

    # ### end Alembic commands ###
