"""Add hero_image field to Post model for hero image selection functionality

Revision ID: a1951ef08ab2
Revises: e47dce8af130
Create Date: 2025-08-15 12:14:35.689872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1951ef08ab2'
down_revision = 'e47dce8af130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('hero_image')

    # ### end Alembic commands ###
