"""Add privacy settings for email and phone sharing

Revision ID: aa28caa1d419
Revises: baa518deda9c
Create Date: 2025-07-10 16:21:01.396462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa28caa1d419'
down_revision = 'baa518deda9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_email', sa.Boolean(), nullable=False, server_default='1'))  # Default to True (allow sharing)
        batch_op.add_column(sa.Column('share_phone', sa.Boolean(), nullable=False, server_default='1'))  # Default to True (allow sharing)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('share_phone')
        batch_op.drop_column('share_email')

    # ### end Alembic commands ###
