"""Add event_id column to bookings table

Revision ID: b9a068d4a434
Revises: 4001c4e8f13c
Create Date: 2025-07-06 18:07:50.955768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a068d4a434'
down_revision = '4001c4e8f13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_bookings_event_id', 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bookings_event_id', type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
