"""Add gender and scoring columns to events table

Revision ID: bb255e71bb7e
Revises: 67edad2468fa
Create Date: 2025-07-07 09:22:48.176482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb255e71bb7e'
down_revision = '67edad2468fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.Integer(), nullable=False, server_default='4'))  # Default to "Open"
        batch_op.add_column(sa.Column('scoring', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('scoring')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
