"""Add last_login and last_seen fields to Member model

Revision ID: c015ca6372d9
Revises: ee9d9d6d823d
Create Date: 2025-07-15 14:16:19.706899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c015ca6372d9'
down_revision = 'ee9d9d6d823d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
