"""Added is_admin field to the user table

Revision ID: d7111c4414f0
Revises: 9ca68375a1c9
Create Date: 2025-04-08 17:07:32.520931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7111c4414f0'
down_revision = '9ca68375a1c9'
branch_labels = None
depends_on = None


def upgrade():
    # Add the column with a default value
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
