"""Drop booking_teams and booking_team_members tables, add teams and team_members tables

Revision ID: dd9e6899e3fd
Revises: 053ed1da1835
Create Date: 2025-07-28 08:17:03.157316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9e6899e3fd'
down_revision = '053ed1da1835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('substitution_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('is_substitute', sa.Boolean(), nullable=False),
    sa.Column('availability_status', sa.String(length=20), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('substituted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('booking_team_members')
    op.drop_table('booking_teams')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_teams',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('booking_id', sa.INTEGER(), nullable=True),
    sa.Column('team_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('substitution_log', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_team_members',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('booking_team_id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.VARCHAR(length=20), nullable=False),
    sa.Column('is_substitute', sa.BOOLEAN(), nullable=False),
    sa.Column('availability_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('substituted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['booking_team_id'], ['booking_teams.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('team_members')
    op.drop_table('teams')
    # ### end Alembic commands ###
