"""Add directory_name field to Post model for new directory-based storage structure

Revision ID: e47dce8af130
Revises: 01623deb0b05
Create Date: 2025-08-14 17:38:40.300533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47dce8af130'
down_revision = '01623deb0b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('directory_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('directory_name')

    # ### end Alembic commands ###
