"""Add availability status enum field

Revision ID: ed9d4c7fe38d
Revises: f1a1f84029b7
Create Date: 2025-07-10 23:11:52.468242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed9d4c7fe38d'
down_revision = 'f1a1f84029b7'
branch_labels = None
depends_on = None


def upgrade():
    # Clean up temp table from previous failed migration
    op.drop_table('_alembic_tmp_booking_team_members')
    
    # Update existing data: convert boolean to enum
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE booking_team_members 
        SET availability_status = CASE 
            WHEN confirmed_available = 1 THEN 'available'
            ELSE 'pending'
        END
        WHERE availability_status IS NULL
    """))
    
    # Make availability_status non-nullable and drop old column
    with op.batch_alter_table('booking_team_members', schema=None) as batch_op:
        batch_op.alter_column('availability_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('confirmed_available')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_team_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_available', sa.BOOLEAN(), nullable=False))
        batch_op.alter_column('availability_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    op.create_table('_alembic_tmp_booking_team_members',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('booking_team_id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.VARCHAR(length=20), nullable=False),
    sa.Column('is_substitute', sa.BOOLEAN(), nullable=False),
    sa.Column('confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('substituted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('availability_status', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['booking_team_id'], ['booking_teams.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
