"""Rename event_owners to event_managers tables

Revision ID: fd3a34e74977
Revises: bb255e71bb7e
Create Date: 2025-07-07 12:22:40.324531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3a34e74977'
down_revision = 'bb255e71bb7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_manager_associations',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_manager_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['event_manager_id'], ['event_managers.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'event_manager_id')
    )
    op.drop_table('event_owners')
    op.drop_table('event_owner_associations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_owner_associations',
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('event_owner_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['event_owner_id'], ['event_owners.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'event_owner_id')
    )
    op.create_table('event_owners',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=15), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('event_manager_associations')
    op.drop_table('event_managers')
    # ### end Alembic commands ###
